### ISSUE TITLE
centos7 start core dump

### ISSUE THREAD

**Issue by zhangzhiming865** [visualfc/liteide#1130]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
liteide-x37.1

### What version of Go are you using (`go version`)?
go1.12.5

### What operating system and processor architecture are you using(`go env`)?
centos7 vmware + x86_64

### What did you do?

If possible, provide a recipe for reproducing the error.

### What did you see instead?
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7abe860 in LiteApp::initPlugins (this=this@entry=0x6e1010) at ../../../liteidex/src/liteapp/liteapp.cpp:714
714	        bool load = m_settings->value(QString("liteapp/%1_load").arg(factory->id()),true).toBool();
Missing separate debuginfos, use: debuginfo-install GConf2-3.2.6-8.el7.x86_64 PackageKit-gtk3-module-1.1.10-2.el7.centos.x86_64 adwaita-qt5-1.0-1.el7.x86_64 at-spi2-atk-2.26.2-1.el7.x86_64 at-spi2-core-2.28.0-1.el7.x86_64 atk-2.28.1-2.el7.x86_64 bzip2-libs-1.0.6-13.el7.x86_64 cairo-1.15.12-4.el7.x86_64 cairo-gobject-1.15.12-4.el7.x86_64 dbus-glib-0.100-7.el7.x86_64 dbus-libs-1.10.24-13.el7_6.x86_64 dconf-0.28.0-4.el7.x86_64 elfutils-libelf-0.176-4.el7.x86_64 elfutils-libs-0.176-4.el7.x86_64 expat-2.1.0-11.el7.x86_64 fontconfig-2.13.0-4.3.el7.x86_64 freetype-2.8-14.el7.x86_64 fribidi-1.0.2-1.el7_7.1.x86_64 gdk-pixbuf2-2.36.12-3.el7.x86_64 glib2-2.56.1-5.el7.x86_64 glibc-2.17-307.el7.1.x86_64 graphite2-1.3.10-1.el7_3.x86_64 gtk3-3.22.30-5.el7.x86_64 gvfs-client-1.36.2-3.el7.x86_64 harfbuzz-1.7.5-2.el7.x86_64 jasper-libs-1.900.1-33.el7.x86_64 jbigkit-libs-2.0-11.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-46.el7.x86_64 libICE-1.0.9-9.el7.x86_64 libSM-1.2.2-2.el7.x86_64 libX11-1.6.7-2.el7.x86_64 libXau-1.0.8-2.1.el7.x86_64 libXcomposite-0.4.4-4.1.el7.x86_64 libXcursor-1.1.15-1.el7.x86_64 libXdamage-1.1.4-4.1.el7.x86_64 libXext-1.3.3-3.el7.x86_64 libXfixes-5.0.3-1.el7.x86_64 libXi-1.7.9-1.el7.x86_64 libXinerama-1.1.3-2.1.el7.x86_64 libXrandr-1.5.1-2.el7.x86_64 libXrender-0.9.10-1.el7.x86_64 libXxf86vm-1.1.4-1.el7.x86_64 libattr-2.4.46-13.el7.x86_64 libblkid-2.23.2-63.el7.x86_64 libcanberra-0.30-9.el7.x86_64 libcanberra-gtk3-0.30-9.el7.x86_64 libcap-2.22-11.el7.x86_64 libcom_err-1.42.9-17.el7.x86_64 libdrm-2.4.97-2.el7.x86_64 libepoxy-1.5.2-1.el7.x86_64 libffi-3.0.13-19.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libgcrypt-1.5.3-14.el7.x86_64 libglvnd-1.0.1-0.8.git5baa1e5.el7.x86_64 libglvnd-egl-1.0.1-0.8.git5baa1e5.el7.x86_64 libglvnd-glx-1.0.1-0.8.git5baa1e5.el7.x86_64 libgpg-error-1.12-3.el7.x86_64 libicu-50.2-3.el7.x86_64 libjpeg-turbo-1.2.90-8.el7.x86_64 libmng-1.0.10-14.el7.x86_64 libmount-2.23.2-63.el7.x86_64 libogg-1.3.0-7.el7.x86_64 libpng-1.5.13-7.el7_2.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64 libtdb-1.3.18-1.el7.x86_64 libthai-0.1.14-9.el7.x86_64 libtiff-4.0.3-32.el7.x86_64 libtool-ltdl-2.4.2-22.el7_3.x86_64 libuuid-2.23.2-63.el7.x86_64 libvorbis-1.3.3-8.el7.1.x86_64 libwayland-client-1.15.0-1.el7.x86_64 libwayland-cursor-1.15.0-1.el7.x86_64 libwayland-egl-1.15.0-1.el7.x86_64 libxcb-1.13-1.el7.x86_64 libxkbcommon-0.7.1-3.el7.x86_64 libxshmfence-1.2-1.el7.x86_64 llvm-private-7.0.1-1.el7.x86_64 lz4-1.7.5-3.el7.x86_64 mesa-dri-drivers-18.3.4-7.el7.x86_64 mesa-libGL-18.3.4-7.el7_8.1.x86_64 mesa-libglapi-18.3.4-7.el7_8.1.x86_64 nss-softokn-freebl-3.44.0-8.el7_7.x86_64 openssl-libs-1.0.2k-19.el7.x86_64 pango-1.42.4-4.el7_7.x86_64 pcre-8.32-17.el7.x86_64 pcre2-utf16-10.23-2.el7.x86_64 pixman-0.34.0-1.el7.x86_64 qgnomeplatform-0.3-5.el7.x86_64 qt5-qtbase-5.9.7-2.el7.x86_64 qt5-qtbase-gui-5.9.7-2.el7.x86_64 qt5-qtimageformats-5.9.7-1.el7.x86_64 qt5-qtsvg-5.9.7-1.el7.x86_64 systemd-libs-219-73.el7.1.x86_64 xcb-util-0.4.0-2.el7.x86_64 xcb-util-image-0.4.0-2.el7.x86_64 xcb-util-keysyms-0.4.0-1.el7.x86_64 xcb-util-renderutil-0.3.9-3.el7.x86_64 xcb-util-wm-0.4.1-5.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  0x00007ffff7abe860 in LiteApp::initPlugins() (this=this@entry=0x6e1010) at ../../../liteidex/src/liteapp/liteapp.cpp:714
#1  0x00007ffff7ac1d6d in LiteApp::load(QString const&, LiteApi::IApplication*) (this=this@entry=0x6e1010, sessionName=..., baseApp=baseApp@entry=0x0)
    at ../../../liteidex/src/liteapp/liteapp.cpp:383
#2  0x00007ffff7ac209d in LiteApp::NewApplication(QString const&, LiteApi::IApplication*) (sessionName=..., baseApp=baseApp@entry=0x0) at ../../../liteidex/src/liteapp/liteapp.cpp:138
#3  0x00007ffff7ab5714 in liteapp_main(int, char**) (argc=1, argv=<optimized out>) at ../../../liteidex/src/liteapp/main.cpp:176
#4  0x00007ffff5a09555 in __libc_start_main () at /lib64/libc.so.6
#5  0x000000000040065e in _start ()

(gdb) p factory
$3 = (LiteApi::IPluginFactory *) 0x0

**Comment by dfbingo** [comment]
我在kvm虚拟机中也出现类似的问题，请问您后来找到解决办法了嘛?
用gdb找到的问题如下：
#0  0x00007fae9c8bb2c8 in LiteApp::initPlugins() () from /usr/local/liteide/bin/../lib/libliteapp.so.1
#1  0x00007fae9c8c4b14 in LiteApp::load(QString const&, LiteApi::IApplication*) () from /usr/local/liteide/bin/../lib/libliteapp.so.1
#2  0x00007fae9c8c51ed in LiteApp::NewApplication(QString const&, LiteApi::IApplication*) () from /usr/local/liteide/bin/../lib/libliteapp.so.1
#3  0x00007fae9c8b350a in liteapp_main(int, char**) () from /usr/local/liteide/bin/../lib/libliteapp.so.1
#4  0x00007fae9c4ab3d5 in __libc_start_main () from /lib64/libc.so.6
#5  0x00000000004005f9 in _start ()

**Comment by zhangzhiming865** [comment]
没有尝试解决。换ide了

**Comment by dfbingo** [comment]
好吧，谢谢
