### ISSUE TITLE
Segmentation fault running under ARM

### ISSUE THREAD

**Issue by dpapathanasiou** [visualfc/liteide#474]
I built from source on an armv7l GNU/Linux (debian) computer, but when I try to run it, the splash screen comes up briefly before seg faulting.

Is there a way to build with a debug flag so I can run the binary under gdb?

I tried that with the binary I have now (output below) but didn't get any insight about the problem.

```
denis@novena:~$ gdb /home/denis/repos/repos-git/liteide/build/liteide/bin/liteide
...
This GDB was configured as "arm-linux-gnueabihf".
...
Reading symbols from /home/denis/repos/repos-git/liteide/build/liteide/bin/liteide...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/denis/repos/repos-git/liteide/build/liteide/bin/liteide 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0xb6f4053a in LiteApp::initPlugins() () from /home/denis/repos/repos-git/liteide/build/liteide/bin/../lib/liteide/libliteapp.so.1
(gdb) backtrace
#0  0xb6f4053a in LiteApp::initPlugins() () from /home/denis/repos/repos-git/liteide/build/liteide/bin/../lib/liteide/libliteapp.so.1
#1  0xb6f42e10 in LiteApp::load(bool, LiteApi::IApplication*) () from /home/denis/repos/repos-git/liteide/build/liteide/bin/../lib/liteide/libliteapp.so.1
#2  0x0000007e in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) frame 2
#2  0x0000007e in ?? ()
(gdb) kill
Kill the program being debugged? (y or n) y
(gdb) quit
```

**Comment by hemantmits** [comment]
I am also seeing this issue on rpi 2 :(
