### ISSUE TITLE
liteide crash in FreeBSD 10/11 amd64 + qt4

### ISSUE THREAD

**Issue by wheelcomplex** [visualfc/liteide#554]
base on https://github.com/visualfc/liteide/commit/94d810adad704f064960e83e257a41b186ac9754

 uname -a: 
FreeBSD freebsd-y570.localdomain 11.0-CURRENT FreeBSD 11.0-CURRENT #0 r292858: Tue Dec 29 07:03:17 UTC 2015     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

[rhinofly@freebsd-y570 ~/liteide/bin]$ ./liteide 
libpng warning: iCCP: profile 'ICC profile': 'GRAY': Gray color space not permitted on RGB PNG
Segmentation fault (core dumped)

github does not allow core dump file to upload ...

**Comment by wheelcomplex** [comment]
build with <pre>-spec freebsd-clang</pre> (change in build_freebsd.sh) will fix the crash in liteide startup, but it's still crash in auto complete.

FreeBSD freebsd-i5-box.localdomain 10.2-STABLE FreeBSD 10.2-STABLE #0 r292855: Tue Dec 29 06:17:50 UTC 2015     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

qt-4.8.7

gdb info:
<pre>
rhinofly@freebsd-i5-box:~/tmp$ gdb710 --core=~/tmp/liteide.core /home/rhinofly/liteide/bin/liteide
GNU gdb (GDB) 7.10 [GDB v7.10 for FreeBSD]
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-portbld-freebsd10.1".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/rhinofly/liteide/bin/liteide...done.
[New process 101677]
[New process 101664]
[New process 101566]
[New process 101549]
[New process 100111]
[New process 100105]
[New process 100104]
[New process 100100]
[New process 100084]
[New Thread 815835c00 (LWP 101664)]
[New Thread 8148ea800 (LWP 101566)]
[New Thread 806415400 (LWP 101549)]
[New Thread 814035800 (LWP 100111)]
[New Thread 806410800 (LWP 100105)]
[New Thread 80640dc00 (LWP 100104)]
[New Thread 80640e400 (LWP 100100)]
[New Thread 80640e000 (LWP 100084)]
[New Thread 806406400 (LWP 101677)]

Core was generated by `liteide'.
Program terminated with signal SIGABRT, Aborted.

#0  0x00000008028ecb7a in thr_kill () from /lib/libc.so.7
[Current thread is 9 (Thread 806406400 (LWP 101677))]
(gdb) 
(gdb) 
(gdb) 
(gdb) bt
#0  0x00000008028ecb7a in thr_kill () from /lib/libc.so.7
#1  0x00000008028ecb66 in raise () from /lib/libc.so.7
#2  0x00000008028ecae9 in abort () from /lib/libc.so.7
#3  0x0000000801a8354b in qt_message_output(QtMsgType, char const*) () from /usr/local/lib/qt4//libQtCore.so.4
#4  0x0000000801a837c9 in ?? () from /usr/local/lib/qt4//libQtCore.so.4
#5  0x0000000801a830dd in qFatal(char const*, ...) () from /usr/local/lib/qt4//libQtCore.so.4
#6  0x000000080df6f665 in QString::at (this=0x7fffffffc5c8, i=16) at /usr/local/include/qt4/QtCore/qstring.h:699
#7  0x000000080df81f48 in LiteCompleter::insertCompletion (this=0x81351baa0, index=...) at ../../../../liteidex/src/plugins/liteeditor/litecompleter.cpp:474
#8  0x000000080df9f3b1 in LiteCompleter::qt_static_metacall (_o=0x81351baa0, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0x7fffffffc840) at .moc/debug-shared/moc_litecompleter.cpp:53
#9  0x0000000801ba3e3d in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/local/lib/qt4//libQtCore.so.4
#10 0x000000080dfa0884 in CodeCompleterEx::activated (this=0x81484b180, _t1=...) at .moc/debug-shared/moc_codecompleter.cpp:238
#11 0x000000080df8ea15 in CodeCompleterEx::completerActivated (this=0x81484b180, index=...) at ../../../../liteidex/src/plugins/liteeditor/codecompleter.cpp:811
#12 0x000000080df8f56d in CodeCompleterEx::eventFilter (this=0x81484b180, o=0x81489f330, e=0x7fffffffcff8) at ../../../../liteidex/src/plugins/liteeditor/codecompleter.cpp:920
#13 0x0000000801b8c8dd in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/local/lib/qt4//libQtCore.so.4
#14 0x0000000800e1184d in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/local/lib/qt4//libQtGui.so.4
#15 0x0000000800e145b2 in QApplication::notify(QObject*, QEvent*) () from /usr/local/lib/qt4//libQtGui.so.4
#16 0x0000000801b8c5d6 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/local/lib/qt4//libQtCore.so.4
#17 0x0000000800e14f0d in ?? () from /usr/local/lib/qt4//libQtGui.so.4
#18 0x0000000800eb0f5d in ?? () from /usr/local/lib/qt4//libQtGui.so.4
#19 0x0000000800eb0c35 in ?? () from /usr/local/lib/qt4//libQtGui.so.4
#20 0x0000000800e87d39 in QApplication::x11ProcessEvent(_XEvent*) () from /usr/local/lib/qt4//libQtGui.so.4
#21 0x0000000800eb2ff1 in ?? () from /usr/local/lib/qt4//libQtGui.so.4
#22 0x00000008030385c8 in g_main_context_dispatch () from /usr/local/lib/libglib-2.0.so.0
#23 0x00000008030388fb in ?? () from /usr/local/lib/libglib-2.0.so.0
#24 0x0000000803038984 in g_main_context_iteration () from /usr/local/lib/libglib-2.0.so.0
#25 0x0000000801bb9121 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/local/lib/qt4//libQtCore.so.4
#26 0x0000000800eb2ccd in ?? () from /usr/local/lib/qt4//libQtGui.so.4
#27 0x0000000801b89bff in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/local/lib/qt4//libQtCore.so.4
#28 0x0000000801b8cb8d in QCoreApplication::exec() () from /usr/local/lib/qt4//libQtCore.so.4
#29 0x0000000800894293 in liteapp_main (argc=2, argv=0x7fffffffe488) at ../../../liteidex/src/liteapp/main.cpp:153
#30 0x000000080089447b in cdrv_main (argc=2, argv=0x7fffffffe488) at ../../../liteidex/src/liteapp/main.cpp:159
#31 0x0000000000400822 in main (argc=2, argv=0x7fffffffe488) at ../../../liteidex/src/liteide/main.cpp:41
(gdb) q
</pre>

**Comment by wheelcomplex** [comment]
closed for too old.
